"""Add route to Bus

Revision ID: bb143de90ffe
Revises: 5065a61656ab
Create Date: 2025-07-24 14:30:55.495175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb143de90ffe'
down_revision = '5065a61656ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bus', schema=None) as batch_op:
        batch_op.add_column(sa.Column('route', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bus', schema=None) as batch_op:
        batch_op.drop_column('route')

    # ### end Alembic commands ###
